/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.pf_desarrollo;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author JuanAntonio
 */
public class ImprimeCert extends javax.swing.JFrame {
    int id;
    /**
     * Creates new form ImprimeCert
     */
    public ImprimeCert(int id){
        initComponents();
        this.id=id;
    }
    private ImprimeCert() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Impresiones de Certificado");

        jLabel2.setText("Id Cliente");

        jLabel3.setText("Lote");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B" }));

        jLabel4.setText("Tipo de Harina");

        jLabel5.setText("Cantidad Solicitada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(77, 77, 77)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String idcliente, lote, tipo, cantidad;
        
        idcliente = jTextField1.getText();
        lote = jTextField2.getText();
        tipo = jComboBox1.getSelectedItem().toString();
        cantidad = jTextField3.getText();
        
        imprime(lote, tipo,cantidad,idcliente);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(id);
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(id);
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void imprime(String lote, String tipo, String cantidad, String idcliente){
        Document cert = new Document();
        boolean truco=false;
        String cliente="";
        String factor1="",res1="";
        String factor2="",res2="";
        String factor3="",res3="";
        
        Statement stmt = null;
        String resultado ="";
        Connection c = null;

        try{
            Class.forName("org.postgresql.Driver");
            c = DriverManager
                .getConnection("jdbc:postgresql://127.0.0.1:5433/a00243504", "a00243504",
                "p14119597");
            c.setAutoCommit(false);
            stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT nombre FROM cliente WHERE id_cliente="+idcliente+";");
            
            while(rs.next()){
                cliente=rs.getString("nombre");
            }
            Statement stmt1 = null;
            stmt1=c.createStatement();
            ResultSet rs1 = stmt1.executeQuery("SELECT * FROM analisis WHERE lote="+lote+" AND harina='"+tipo+"';");
            
            while(rs1.next()){
                factor1 = rs1.getString("factor1");
                factor2 = rs1.getString("factor2");
                factor3 = rs1.getString("factor3");
                
                res1 = rs1.getString("resultado1");
                res2 = rs1.getString("resultado2");
                res3 = rs1.getString("resultado3");
            }
            
        }catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al conectarse a la base de datos"+e.toString());
            System.exit(0);
        }
        
        try{
            PdfWriter writer = PdfWriter.getInstance(cert, new FileOutputStream("Cert_"+cliente+".pdf"));
            cert.open();
            
            Paragraph Titulo = new Paragraph("Fabricas Harinas Elizondo S.A. de C.V.");
            Titulo.setAlignment(Element.ALIGN_CENTER);
            cert.add(Titulo);
            
            Paragraph Cliente = new Paragraph("Cliente: "+cliente);
            cert.add(Cliente);
                    
            Paragraph Lote = new Paragraph("Lote: "+lote);
            cert.add(Lote);
            
            Paragraph Tipo = new Paragraph("Tipo de Harina: "+tipo);
            cert.add(Tipo);
            
            Paragraph Cantidad = new Paragraph("Cantidad Solicitada: "+cantidad+"KG");
            cert.add(Cantidad);
            
            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10f);
            table.setSpacingAfter(10f);
            
            float[] columnwidths = {1f,1f};
            table.setWidths(columnwidths);
            
            PdfPCell celda1 = new PdfPCell(new Paragraph("Factor de Análisis"));
            celda1.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            PdfPCell celda2 = new PdfPCell(new Paragraph("Resultados"));
            celda2.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            PdfPCell celda3 = new PdfPCell(new Paragraph(""+factor1));
            celda3.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            PdfPCell celda4 = new PdfPCell(new Paragraph(""+res1));
            celda4.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            PdfPCell celda5 = new PdfPCell(new Paragraph(""+factor2));
            celda5.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            PdfPCell celda6 = new PdfPCell(new Paragraph(""+res2));
            celda6.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            PdfPCell celda7 = new PdfPCell(new Paragraph(""+factor3));
            celda7.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            PdfPCell celda8 = new PdfPCell(new Paragraph(""+res3));
            celda8.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            table.addCell(celda1);
            table.addCell(celda2);
            table.addCell(celda3);
            table.addCell(celda4);
            table.addCell(celda5);
            table.addCell(celda6);
            table.addCell(celda7);
            table.addCell(celda8);
            
            cert.add(table);
            
            Paragraph Firma = new Paragraph("___________________________________");
            Firma.setAlignment(Element.ALIGN_RIGHT);
            cert.add(Firma);
            
            Paragraph Responsable = new Paragraph("Responsable");
            Responsable.setAlignment(Element.ALIGN_RIGHT);
            cert.add(Responsable);
            
            Paragraph Fecha = new Paragraph("México a "+java.time.LocalDate.now());
            Fecha.setAlignment(Element.ALIGN_BOTTOM);
            cert.add(Fecha);
            
            cert.close();
            writer.close();
            JOptionPane.showMessageDialog(null,"Certificado creado con el nombre Cert_"+cliente);
            
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            
            
        }catch(DocumentException e){
            JOptionPane.showMessageDialog(null, "Error al crear el certificado");
        }catch (FileNotFoundException e){
            JOptionPane.showMessageDialog(null, "Error al crear el certificado");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimeCert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimeCert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimeCert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimeCert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImprimeCert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
